worker_processes 1;
daemon on;
pid /home/j/kimai/ant/nginx.pid;

events {
    worker_connections 1024;
}

http {
    access_log /home/j/kimai/ant/access.log;
    error_log /home/j/kimai/ant/error.log;
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    server {
        listen 8080;
        server_name localhost;

        root /home/j/kimai/ant;
        index index.html;

        location / {
            try_files $uri $uri/ =404;
        }
    }
}
